image: ruby:2.7.5
services:
  - postgres:9.5
variables:
  POSTGRES_DB: jobvacancy_test
  POSTGRES_USER: jobvacancy
  POSTGRES_PASSWORD: jobvacancy
  DB_HOST: postgres
  TEST_DB_URL: postgres://jobvacancy:jobvacancy@postgres/jobvacancy_test
stages:
  - build
  - deploy_staging
  - deploy_production

job_build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
    - ruby -v
    - which ruby
    - gem install bundler -v 2.1.4 --no-document
    - bundle install --without staging production
    - RACK_ENV=test bundle exec rake

job_deploy_staging:
  stage: deploy_staging
  script:
  - gem install dpl
  - dpl --provider=heroku --app=saltajobvacancystaging --api-key=78276cb8-f534-4f03-b000-61059b862e61
  only:
  - staging

job_deploy_production:
  stage: deploy_production
  script:
  - gem install dpl
  - dpl --provider=heroku --app=saltajobvacancyproduction --api-key=78276cb8-f534-4f03-b000-61059b862e61
  only:
  - master